# Generated by Django 2.1 on 2022-04-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wing',
            field=models.CharField(blank=True, choices=[('Dublin', 'Dublin'), ('Cork', 'Cork'), ('Galway', 'Galway')], max_length=10),
        ),
    ]
